# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usr_City',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
